<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students [
  <!ELEMENT students (student+)>
  <!ELEMENT student (name, address+, phone, website)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT address (#PCDATA)>
  <!ATTLIST address type (permanent|temporary) #REQUIRED>
  <!ELEMENT phone (#PCDATA)>
  <!ELEMENT website (#PCDATA)>
  <!ENTITY % digits "[0-9]">
  <!ENTITY % phoneNumber>
  <!ELEMENT phoneNumber (#PCDATA)>
  <!ATTLIST phoneNumber type (home|work|mobile) #IMPLIED>
  <!ELEMENT phone (%phoneNumber;)>
]>
<students>
  <student>
    <name>Roshan Limbu</name>
    <address type="permanent">123 Main Street</address>
    <address type="temporary">456 Elm Street</address>
    <phone>9811983456</phone>
    <website>www.roshanlimbu.com</website>
  </student>
  <student>
    <name>Oshan Limbu</name>
    <address type="permanent">Sundarharaich 1, Morang</address>
    <phone>9811983456</phone>
    <website>www.oshanlimbu.com</website>
  </student>
</students>
