<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE Books [
<!ELEMENT Books (Book+)>

<!ELEMENT Book (Title?, Isbn+, (Zipcode | Author), Publish*)>

<!ELEMENT Title (#PCDATA)>
<!ELEMENT Isbn (#PCDATA)>
<!ELEMENT Zipcode (#PCDATA)>
<!ELEMENT Author (#PCDATA)>
<!ELEMENT Publish (#PCDATA)>
<!ATTLIST Title
Name CDATA #IMPLIED>

<!ATTLIST Isbn No CDATA #REQUIRED>

<!ATTLIST Zipcode Zname CDATA #FIXED "232232323">

<!ATTLIST Publish Year CDATA #FIXED "1995">
]>


<Books>
  <Book>
    <Title>Harry potter</Title>
    <Isbn No="123">123</Isbn>
    <Author>J.K Rowling</Author>
    <Publish>W.B</Publish>
    <Publish>Disney</Publish>
  </Book>
</Books>
