<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE TVSCHEDULE [
<!ELEMENT TVSCHEDULE (Channel+)>

<!ELEMENT Channel (Banner, Day+)>


<!ELEMENT Banner (#PCDATA)>
<!ELEMENT Day (Date, (Holiday|Programslot)+)><!--  * here if the question had asked zero or more occurence -->
<!ELEMENT Date (#PCDATA)>
<!ELEMENT Holiday (#PCDATA)>

<!ELEMENT Programslot (Time, Title, Description?)>
<!ELEMENT Time (#PCDATA)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Description (#PCDATA)>

<!ATTLIST TVSCHEDULE
Name CDATA #REQUIRED>

<!ATTLIST Channel
Chan CDATA #REQUIRED>

<!ATTLIST Programslot
Vtr CDATA #IMPLIED>

<!ATTLIST Title
Rating CDATA #IMPLIED
Language CDATA #IMPLIED>

]>

<TVSCHEDULE Name="Weekely show">
  <Channel Chan="Discovery">
    <Banner>This is my show.</Banner>
    <Day>
      <Date>2022-12-25</Date>
      <Holiday>Christms Holiday</Holiday>
    </Day>
    <Day>
      <Date>2023-01-01</Date>
      <Programslot Vtr="123">
        <Time>07:30</Time>
        <Title>Sunday Morninig News</Title>
        <Description>Sunay Morning News</Description>
      </Programslot>
    </Day>
  </Channel>
</TVSCHEDULE>
